# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "19844c9ee88f0e6073fe82442238473a"
application_url = "https://example.com"
embedded = true
name = "dynamic-variant-specs"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_metaobjects,write_metaobject_definitions"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2026-07"
